# Dockerfile simple pour Streamlit
FROM python:3.12-slim

WORKDIR /app

# Installation des dépendances
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copie du frontend
COPY frontent/ ./frontent/

# Port Streamlit
EXPOSE 8501

# Démarrage Streamlit
CMD ["streamlit", "run", "frontent/app.py", "--server.address=0.0.0.0", "--server.port=8501"]