# API sur api.apartment-hunter.lab.zanza-creation.com
# Streamlit sur apartment-hunter.lab.zanza-creation.com
# ZÉRO PathPrefix
# ZÉRO StripPrefix
# ZÉRO RedirectRegex
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: apartment-api
    expose:
      - "8000"
    volumes:
      - ./models:/app/models:ro
      - ./data_model:/app/data_model:ro
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apartment-api.rule=Host(`api.apartment-hunter.lab.zanza-creation.com`)"
      - "traefik.http.routers.apartment-api.entrypoints=websecure"
      - "traefik.http.routers.apartment-api.tls.certresolver=myresolver"
      - "traefik.http.services.apartment-api.loadbalancer.server.port=8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    container_name: apartment-front
    environment:
      # Injecte l'URL publique
      - API_URL=https://api.apartment-hunter.lab.zanza-creation.com/predict
    expose:
      - "8501"
    depends_on:
      - api
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apartment-front.rule=Host(`apartment-hunter.lab.zanza-creation.com`)"
      - "traefik.http.routers.apartment-front.entrypoints=websecure"
      - "traefik.http.routers.apartment-front.tls.certresolver=myresolver"
      - "traefik.http.services.apartment-front.loadbalancer.server.port=8501"
    restart: unless-stopped

networks:
  traefik:
    external: true